### ISSUE TITLE
The purpose of oct_preprocess

### ISSUE THREAD

**Issue by zhilingxuQsQ** [heyufan1995/oct_preprocess#2]
Why we have to flatten the BM/RPE before we do the following segmentation task or other tasks? Whether it is necessary to improve the  accuracy of retina segmentation?

**Comment by heyufan1995** [comment]
The initial purpose is to reduce the GPU memory, because the B-scans are too large.  I feel like it's okay to skip the flattening if GPU memory is enough nowadays.
