### ISSUE TITLE
License

### ISSUE THREAD

**Issue by charleneolive** [heyufan1995/oct_preprocess#3]
Can I ask what is the license for this code?

**Comment by aaroncarass** [comment]
No commercial use.

Just acknowledge the publication:
"Intensity inhomogeneity correction of SD-OCT data using macular flatspace"
A. Lang, A. Carass, B.M. Jedynak, S.D. Solomon, P.A. Calabresi, J.L. Prince
Medical Image Analysis 43, 85-97, 2018.
https://doi.org/10.1016/j.media.2017.09.008
